Yubico/libfido2

- src/cbor.c
It seems like libfido2 is not correctly encoding small COSE algorithm values.
From what I understand, a device does not have the obligation to enforce those encoding rules and this is why the Yubikey 5 NFC does work even without this modification.
However the BioPass FIDO2 is stiffer and so does not allow for algorithm values < -25 encoded with an additional uint16_t.
This solves https://github.com/Yubico/libfido2/issues/10
Ref.:
FIDO 2.0: Client To Authenticator Protocol
6. Message encoding
Integers must be encoded as small as possible.
0 to 23 and -1 to -24 must be expressed in the same byte as the major type;
24 to 255 and -25 to -256 must be expressed only with an additional uint8_t;
> Encode COSE Algorithm as per spec

- udev/70-old-u2f.rules
- udev/70-u2f.rules
This is backported from libu2f-host.
Even though it's an easy thing, it's been done through
```
git show 15c6ca2 > udev.patch
patch -p1 -i udev.patch
```
to be on the safe side.
> Add BioPass FIDO2 to udev rules

- examples/manifest.c
- tools/token.c
Cast vendor and device ID to uint16_t.  Previously vendor or device IDs
0x8000 or greater were displayed with a 0xffff prefix - for example,
product=0xffffa2ca.
> Avoid sign extension when printing USB vendor or device ID

- src/assert.c
- src/fido.h
This allows access to the signature counter in an assertion statement
and is useful when implementing a standalone verifier.
> Add a fido_assert_sigcount() function

- tools/CMakeLists.txt
- tools/sk-libfido2.c
This adds libsk-libfido2.so that may be used by recent OpenSSH to
talk to U2F/FIDO2 tokens.
I'm not sure the cmake bits are 100% correct, it spits out "libsk-libfido2.so" rather than the "sk-libfido2.so" I expected, but I'm not bothered by that.
> Middleware library for use by OpenSSH

- man/fido.3
- man/fido2-cred.1
..also remove trailing whitespace from fido2-cred man page.
> man: remove text about non-existing _FIDO_DEBUG compile-time option

- openbsd-compat/openbsd-compat.h
- src/u2f.c
This is a standalone fix for the endianness issue mentioned in #82.
The attested credential data uses big-endian encoding for the `credentialIdLength`:
https://www.w3.org/TR/webauthn/#sec-attested-credential-data
> fix attcred_raw.id_len on big-endian systems

- tools/CMakeLists.txt
- tools/sk-libfido2.c
- tools/sk-libfido2.h
Factor out a header for convenient inclusion of this middleware, and also rename function parameters for readability.
> Sk libfido2 header

- .github/workflows/scan.yml
This only runs on push for now so PRs are not covered. PRs are special in that if it comes from a fork it does not have access to the docker registry secrets in the repo but I have found no way of testing for the presence from within a github flow.
As of today the scanners show no warnings.
> adding a static code analysis github workflow

- fuzz/fuzz_assert.c
- fuzz/fuzz_bio.c
- fuzz/fuzz_cred.c
- fuzz/fuzz_credman.c
- fuzz/fuzz_mgmt.c
- regress/assert.c
- regress/cred.c
- regress/dev.c
- src/dev.c
- src/extern.h
- src/fido/types.h
- src/hid_hidapi.c
- src/hid_linux.c
- src/hid_openbsd.c
- src/hid_osx.c
- src/hid_win.c
- src/io.c
This branch is based on `custom-device-info-manifest`:
- adds `fido_dev_io_tx_t` and `fido_dev_io_rx_t` to `fido_dev_io_t`
- Defaults the two new i/o functions to the original `fido_tx` and `fido_rx` functions.
Combined with the changes in `custom-device-info-manifest`, this will allow easy registration of custom transport layers (e.g. BLE).
> Custom transport

- src/u2f.c
Hi, Pedro,
This change is intended to let fido_dev_get_assert records the key_id in the attstmt_t for check-only cases as well. We believe this is a common use case (a user has a sequence of key_ids from the rp and they want to check which one of them is valid for the device, without a user touch).
> Record keyid for checkonly

- src/CMakeLists.txt
- src/dev.c
- src/log.c
This makes the xxd message stay in the same line in some log system.
E.g in windows syslog, each call will occupy one line in the log system.
> Make fido_log_xxd call log_handler once per line.

- src/log.c
GCC 8 and GCC 9 both are uncomfortable with the snprintf'ing
of format string "%04zu: %02x" fitting into 16 bytes,
and it's unclear to me this is an unwarranted concern.
If the buffer is indeed too small, the result would not
be a memory safety error AFAIK but the truncated string
would provide poor log messages.
Likely harmless but instead of worrying about any of that
just allocate a few more bytes to make it clear to programmers and
compilers alike that there's nothing to worry about.
> src/log.c: bump XXDLEN 16->32 to ensure buffer isn't too small

- src/blob.h
- src/extern.h
- src/fido.h
- src/fido/bio.h
- src/fido/credman.h
- src/fido/eddsa.h
- src/fido/err.h
- src/fido/es256.h
- src/fido/rs256.h
- src/fido/types.h
- src/iso7816.h
Linking libfido2 into a C++ project will fail, as the headers
are missing the 'extern "C"' declarations - thus, the linker will
assume C++ name wrangling and fail to find the invoked functions into
libfido2.so. Add extern "C" to all declarations inside header files.
> headers: Add 'extern "C"' declarations for C++ support.

- man/CMakeLists.txt
LOCALBASE/share/man is a valid path for manpages since [r523104](https://svnweb.freebsd.org/changeset/ports/523104).
> Update FreeBSD manpage location

- CMakeLists.txt
- examples/CMakeLists.txt
- openbsd-compat/readpassphrase.c
- tools/CMakeLists.txt
#132 asked for it. So this is my take.
Actually I found some interesting quirks, that could be problematic in other cases as well, e.g. using _NSIG instead of NSIG.
And that defining -std=c99 you don't get some some functions like strdup, so I defined _DEFAULT_SOURCE as I guess this does not hurt to make sure they are in...
> Add MSYS and CYGWIN build support

- CMakeLists.txt
It avoid manually setting "LDFLAGS+= -lusbhid" in the ports Makefile.
> Add FreeBSD support for usbhid library detection

- man/fido_bio_dev_get_info.3
- man/fido_credman_metadata_new.3
Since I complained about the documentation in #129 , maybe it makes sense to add a least a word of warning that the functions are not included in the current spec.
> Warn fido21 pre

- tools/credman.c
The message should say "remaining" instead of "possible" RKs.
Fixes issue #147
> tools: fix the message for resident credentials metadata

- CMakeLists.txt
- src/hid_openbsd.c
Only change is we keep using the USB_GET_DEVICEINFO ioctl,
OpenBSD removed it to be more pledge friendly.
> hid_openbsd: synchronize changes from OpenBSD

- man/CMakeLists.txt
calling gzip without -n breaks reproducible builds
see the following for more info:
https://wiki.debian.org/ReproducibleBuilds/TimestampsInGzipHeaders
> call gzip with -n argument for manpages

- openbsd-compat/types.h
- src/fido.h
This addresses 2 problems that I've found:
* ```__attribute__``` isn't available, use ```__declspec``` instead
* The ```uid_t``` and ```mode_t``` types conflict for example with Perl's typedefs. Other projects also seem to chose the types I suggest:
References:
* https://gitlab.kitware.com/cmake/cmake/-/blob/001043ac3078c49651f6af0f1ff1b31ef71a7665/Source/cmStandardIncludes.h#L56
* https://fossies.org/linux/perl/win32/win32.h
* https://github.com/llvm-git-prototype/llvm/blob/master/lldb/include/lldb/Host/windows/PosixApi.h#L76
> MSVC Fixes

- CMakeLists.txt
- fuzz/mutator_aux.c
- src/dev.c
- src/extern.h
- src/fido/param.h
- src/fido/types.h
- src/hid_hidapi.c
- src/hid_linux.c
- src/hid_openbsd.c
- src/hid_osx.c
- src/hid_win.c
- src/io.c
Currently, the lengths of the HID input/output reports are hardcoded as
64 bytes both in the backends and the rx/tx logic in io.c.
This commit makes the report lengths configurable in all these places
without affecting the public API. The report lengths are kept in
`report_{in,out}_len fields` in fido_dev_t and are obtained from the
included backends via fido_hid_report_{in,out}_len() functions. The use
of these functions is gated on a `fixed_rpt_size` flag in fido_dev_t
that could be exposed to custom i/o functions in a future commit.
While the report lengths become configurable with this commit, they are
still kept at the default 64 bytes in all backends. Future commits to
the individual backends will add the logic that extracts the report
lengths from the HID report descriptor.
> Make report lengths configurable in rx/tx/backends

- src/hid_linux.c
Extracts input and output report lengths from the report descriptor
by parsing it manually.
Since the previous implementation did not parse the report lengths out
of the report descriptor, any failure causes a fallback to the default
64 bytes in order to ensure backward compatibility.
This has been tested manually with both a 64 byte and a 62 byte FIDO device.
> Read report lengths from descriptor on Linux

- fuzz/fuzz_credman.c
- src/credman.c
- tools/credman.c
The credProtect level of a resident credential is returned under the
key 0x0A (10) of a credential management response. With this commit,
the value is parsed and can be read with fido_cred_prot.
> Extract credProtect from credman response

- src/dev.c
Since fido_dev_t and the backends separately maintain the report
lengths, fido_dev_open_tx cannot unilaterally fall back to 64 bytes and
has to fail if it encounters an invalid report length.
With this change, the backends no longer have to perform any checks on
report lengths extracted from the report descriptor. They may however
choose to do so to help them decide whether or not a device is a valid
FIDO device.
> Fail in fido_dev_open_tx on invalid report lengths

- src/hid_win.c
Extracts input and output report lengths from the report descriptor
using HidP_GetCaps.
Since the previous implementation rejected all devices with report
lengths other than 64 bytes (+ report ID), we can reject devices with
invalid report lengths without affecting backward compatibility.
This has been tested lightly tested with both a 64 byte and a 62 byte FIDO device, further testing will be done after #181 has been resolved.
> Read report lengths from descriptor on Windows

- src/hid_osx.c
Extracts input and output report lengths from the report descriptor.
Since the previous implementation rejected all devices with input
report lengths other than 64 bytes, we can reject devices with
invalid report lengths without significantly affecting backward
compatibility - only devices with non-standard HID descriptors that
nonetheless declared a valid input report could be affected negatively.
I confirmed that this builds in the CI, but am unfortunately unable to test it since I lack access to a macOS device.
> Read report lengths from descriptor on macOS

- src/hid_linux.c
Previously, hid_linux.c would fail to extract product and manufacturer
for Bluetooth HID devices since they are not available as individual
sysattrs.
With this commit, the product name is parsed from the uevent sysattr
while the manufacturer, which is not exposed by the kernel, is set to a
descriptive constant ("Bluetooth HID").
I have verified that with this and #168, libfido2 can speak to and detect WearAuthn:
<details>
<summary>Screenshots</summary>
</detail>
> Add support for Bluetooth HID devices to hid_linux

- README.adoc
pkg-config is needed for the calls to `pkg_search_module` in https://github.com/Yubico/libfido2/blob/master/CMakeLists.txt
See https://cmake.org/cmake/help/latest/module/FindPkgConfig.html
> Add note about `pkg-config` to the readme

- tools/fido2-unprot.sh
Adds `fido2-unprot` which scans attached security keys for resident
credentials that do not require user verification to be enumerated.
If a security key does not support Credential Management, the script
only checks whether there is a unprotected resident SSH credential
created with default settings. Detecting the latter is the primary
usecase of this script.
> Add tool detecting unprotected resident credentials

- tools/fido2-unprot.sh
Improves fido2-unprot in the following ways:
* Use global fido2-* binaries (override with FIDO_TOOLS_PREFIX)
* Exit if it is not running on Linux
* Exit if libfido2 is not installed or not recent enough
* Exit if an error occurs
Signed-off-by: Gabriel Kihlman <g.kihlman@yubico.com>
> Improve fido2-unprot script compatibility

- fuzz/export.gnu
- fuzz/fuzz_cred.c
- man/CMakeLists.txt
- man/fido_cred_new.3
- src/cred.c
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido.h
This function can be used to get the authenticator data signature
counter of a credential, e.g. for reconstructing the authdata payload
when verifying the credential.
> Introduce function fido_cred_sigcount()

- .github/workflows/cifuzz_oss.yml
- .github/workflows/linux_builds.yml
Sadly, the format of the (sparse) build matrix is quite verbose. If anyone has any better idea on how to loop over valid OS/compiler combinations, that would be very helpful!
> ci: restrict where cifuzz_oss runs, add more environments to linux_builds

- src/CMakeLists.txt
- src/dev.c
- src/extern.h
- src/random.c
Moving the random generation will be useful for cases where we will need to
generate random byte sequences for different use-cases than the nonce.
Checking the return value of `getrandom()` ensures that we got the correct
number of random bytes returned from the function (e.g if the call was 
interrupted by a signal handler).
> random: move random generation to own source file, check return of getrandom()

- .github/workflows/linux_builds.yml
- .github/workflows/linux_fuzz.yml
GitHub appears to have fixed their environments. Refer to pull requests
actions/virtual-environments#1729 and actions/virtual-environments#1667.
This reverts commit f9d4642255efb1cf3e2ba8d4cd47f85462a6bcc8.
> workflows: enable ubuntu-20.04 + clang-10 builds again

- .github/workflows/codeql-analysis.yml
This job will fail on repositories which do not have CodeQL enabled with
the error message
Error: init action failed: HttpError: repository not enabled for
code scanning
Instead of generating an error, skip the job if the pipeline runs in
another repository than yubico/libfido2.
> workflows: only run codeql analysis on yubico/libfido2

- src/hid_win.c
This fixes an `undefined symbol wcsncmp' on Cygwin.
> src/hid_win.c: add missing #include <wchar.h>

- src/cbor.c
According to the CTAP2 canonical CBOR encoding form, keys in every map
must be sorted lowest value to highest. For string keys, this means
shorter keys should sort earlier, and lower-value in byte-wise lexical
order sorts earlier. The latter was incorrect for encoding extensions
for fido_cred_t and is fixed with this change.
> cbor: fix ordering of cbor_encode_extensions

- fuzz/export.gnu
- fuzz/fuzz_credman.c
- man/CMakeLists.txt
- man/fido_dev_open.3
- src/dev.c
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/extern.h
- src/fido.h
This function can be used to query the authenticator support for FIDO
2.1 Credential Management.
> dev: add fido_dev_supports_credman()

- udev/70-u2f.rules
- udev/fidodevs
Hi!
With this PR I would like to add Udev rule for Nitrokey 3C NFC.
cc @Nitrokey
> udev: add Nitrokey 3C NFC

- udev/70-u2f.rules
- udev/fidodevs
According to https://www.trustkeysolutions.com/support/ two new products
T110 and T120 are added. The formerly eWBM G310, G320 are now under the
Trustkey brand.
> Add/Update Trustkey T110, T120, G310, G320

- fuzz/export.gnu
- fuzz/fuzz_mgmt.c
- man/CMakeLists.txt
- man/fido_dev_set_pin.3
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido.h
- src/pin.c
- tools/token.c
This retrieves the number of built-in UV attempts before built-in UV is
disabled on the device.
> pin: add fido_dev_get_uv_retry_count()

- man/CMakeLists.txt
- man/fido_assert_set_authdata.3
- src/assert.c
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido.h
Useful for testing applications that use the hmac-secret.
fix https://github.com/Yubico/libfido2/issues/256
> New function fido_assert_set_hmac_secret.

- udev/70-u2f.rules
- udev/fidodevs
Hi, with this PR a udev rule for a new fido device `Canokey` is added. Please check @Canokeys for more info!
Also, the vendor is changed from `Flirc` to `Clay Logic` as `Clay Logic` is the correct holder of the vendorID.
> udev: Add CanoKey and Update to correct vendor

- .actions/build-linux-clang
- .actions/build-linux-gcc
- .actions/build-linux-i686-w64-mingw32-gcc
- .actions/build-osx-clang
- .actions/fuzz-linux
- .github/workflows/alpine_builds.yml
Each virtual machine on GitHub has two available cores. Parallel jobs on
Windows did not seem to improve build times.
> actions: build with 2 simultaneous jobs

- udev/70-u2f.rules
- udev/fidodevs
https://www.gotrustid.com/faqs-of-idem-key
https://download.gotrustid.com/Idem/IdemKey/70-u2f.rules
Signed-off-by: Michal Suchanek <msuchanek@suse.de>
Only based on the rules file - not tested.
> udev: Add alternative ID for GoTrust Idem Key

- .actions/fuzz-linux
- .github/workflows/linux_fuzz.yml
please note that this PR deliberately omits the execution of `fuzz_largeblob` from `.actions/fuzz_linux`, since it depends on `corpus.tgz` being synced, which will take a couple of days longer.
> actions/fuzz: build zlib with asan/msan

- tools/token.c
otherwise `fido2-token -Gbn rp_id /dev/hidraw2` will fetch the blob from _and_ write it to /dev/hidraw2. fido2-token.c and its argc/argv handling need a revamp after 1.7.0; PRs welcome.
> fido2-token: ensure a blob path is provided in token_get()

- fuzz/libfuzzer.c
move the check to the beginning of LLVMFuzzerTestOneInput() as per
https://github.com/google/oss-fuzz/pull/5406#discussion_r595312235
> fuzz: move size > 4096 check

- fuzz/wrap.c
- fuzz/wrapped.sym
N.B. please double-check that the return values listed in wrap.c are correct.
> fuzz: wrap a few more libcrypto symbols

- src/credman.c
- src/largeblob.c
so that the authenticator has a chance to reply with `FIDO_ERR_PIN_REQUIRED`, as per spec. this is a sensible thing to do on its own, but also required for `fido2-token` to work as expected with PIN authenticaton after https://github.com/Yubico/libfido2/commit/6c1d0886e2d8451b857505744b5b83583924c38b.
> credman: allow requests without a pin/uv token through

- src/assert.c
- src/pin.c
calling `fido_dev_can_get_uv_token()` from the module's `tx()` function is typically ok, but assertions are a special case: we obtain a ecdh shared secret in the very beginning, and hold on to it while making multiple trips to the authenticator, so that we can gather all the assertions and decrypt any hmac secrets. we should therefore move the call to `fido_dev_can_get_uv_token()` from `tx()` to the outer `fido_dev_get_assert()`, where the call to `fido_do_ecdh()` takes place.
> assert: fix use of fido_dev_can_get_uv_token()

- src/assert.c
we need to call fido_dev_can_get_uv_token() prior to
cbor_add_uv_params(), or we break the hmac-secret w/o pin/uv case.
in 8715f33, i assumed that hmac-secret implied pin/uv. perhaps that
used to be the case, but it is no longer true.
> assert: tweak 8715f33

- src/log.c
log.c's do_log() contains a silent (and harmless) snprintf() truncation. This truncation triggers gcc's `-Wformat-truncation` when combined with `-O3 -D_FORTIFY_SOURCE=2` and glibc headers, as reported in #318; `-O3` is [enabled by CMake](https://github.com/Kitware/CMake/blob/a24a4e18af1d40d6bf81045c5955aa08b5e51797/Modules/Compiler/GNU.cmake#L58) on CMAKE_BUILD_TYPE=Release builds, while we [set](https://github.com/Yubico/libfido2/blob/d3ed2bfc1172074f81ce04973f33db532c4ec141/CMakeLists.txt#L268) `-D_FORTIFY_SOURCE=2` on CMAKE_BUILD_TYPE=Release builds. This PR embeds the truncation in the format string, making it explicit and suppressing the warning. I haven't checked why the warning does not happen with `-O2`.
Edit: accuracy
> Explicitly truncate log entries to silence gcc

- .actions/build-bsd
- .actions/build-linux-clang
- .actions/build-linux-gcc
- .actions/build-osx-clang
For every CI workflow (except Windows), build libfido2 twice: once with CMAKE_BUILD_TYPE=Debug and once with CMAKE_BUILD_TYPE=Release. Please note that this PR depends on #319.
> actions: build with CMAKE_BUILD_TYPE=Release

- src/CMakeLists.txt
populate TARGET_LIBRARIES once and use it in the definition of the static and shared lib targets, instead of duplicating the contents of TARGET_LIBRARIES in both places.
> cmake: remove code duplication

- src/libfido2.pc.in
While there may be a point in defining 'Requires.private', it is ultimately the territory of package maintainers and wasn't the commit's intention; 'Libs.private' was intended.
Due to CMake's architecture and the concept of a separate "generator", expanding 'Libs.private' from within CMakeLists.txt isn't trivial. While there are some acrobatics we could do, they are likely to produce innacurate results.
> pkg-config: revert 4b9ff83

- tools/util.c
prompt for a pin and retry the operation if the key returns `FIDO_ERR_UV_BLOCKED`.
> tools: retry with pin on FIDO_ERR_UV_BLOCKED

- src/extern.h
- src/info.c
and use it in `fido_dev_get_cbor_info_rx()` instead of just zeroing the structure and potentially leaking memory.
> define fido_cbor_info_reset()

- src/winhello.c
Please note that Microsoft's `webauthn.h` allows a credential to be created with the `hmac-secret` extension enabled, but does not allow subsequent assertions to obtain the secret.
> winhello: support credential generation with hmac secret

- fuzz/export.gnu
- fuzz/fuzz_cred.c
- man/CMakeLists.txt
- man/fido_cred_set_authdata.3
- src/cred.c
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido.h
`fido_cred_set_id()` allows a credential's id to be set in contexts where authdata is unavailable but operations on a fido_cred_t are still desired (e.g. credential management).
> introduce fido_cred_set_id()

- src/assert.c
- src/config.c
- src/cred.c
- src/credman.c
- src/extern.h
- src/largeblob.c
- src/pin.c
`fido_dev_can_get_uv_token()` centralised the logic determining whether to retrieve a uv token from the authenticator. As it happens, CTAP 2.1 is nuanced enough that holding such logic in a single place becomes impractical. This PR replaces `fido_dev_can_get_uv_token()` with ad-hoc language. Discussed with and feedback from @LDVG.
> retire fido_dev_can_get_uv_token()

- fuzz/export.gnu
- fuzz/fuzz_credman.c
- man/CMakeLists.txt
- man/fido2-token.1
- man/fido_credman_metadata_new.3
- src/credman.c
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido/credman.h
- tools/credman.c
- tools/extern.h
- tools/fido2-token.c
- tools/token.c
A counterpart of `fido_credman_set_dev_rk()` to update/set certain parts of a resident credential (only name/displayName for now).
> credman: introduce fido_credman_set_dev_rk()

- src/winhello.c
- allow NULL as an rp name (since it's optional);
- allow up=omit and up=true (which are winhello's default).
> winhello: minor tweaks

- src/io.c
If multiple applications are accessing a single device both would error
out since they'd intercept frames with the wrong channel identifier
(cid). Instead, discard all frames with the wrong cid and loop until we
receive the response to our message.
> io: discard frames with wrong channel identifier

- .actions/build-linux-i686-w64-mingw32-gcc
- .actions/fuzz-linux
This slightly speeds up clone/checkout time.
> ci: use shallow git clones of libcbor,openssl,zlib

- src/hid_linux.c
use a polynomial backoff algorithm (exponent ~2, scale factor ~1/20) and flock() to serialise access to HID devices on Linux with a timeout of 12 seconds. prompted by https://github.com/systemd/systemd/issues/19842.
> hid_linux: implement a thin synchronisation mechanism

- src/config.c
ctap 2.1 keys support uv permissions, but may not have a pin configured; found the hard way by kostas@.
> config: allow requests without uv on ctap 2.1 keys

- fuzz/export.gnu
- fuzz/fuzz_hid.c
- fuzz/udev.c
- fuzz/wrapped.sym
- src/CMakeLists.txt
wrap enough of libudev to allow the fuzzing of `fido_hid_manifest()` and `fido_nfc_manifest()` on linux. short of using libudev directly (which is impractical due to its behaviour being filesystem bound), this approach is probably the best we can do.
> fuzz_hid: fuzz udev bits

- examples/cred.c
- man/fido_cred_set_authdata.3
- man/fido_cred_verify.3
- regress/cred.c
- src/cbor.c
- src/cred.c
- src/winhello.c
support attestation format 'none', specified in https://www.w3.org/TR/webauthn-2/#sctn-none-attestation.
> support attestation format 'none'

- .github/workflows/windows.yml
- CMakeLists.txt
- openbsd-compat/readpassphrase_win32.c
- src/hid.c
- src/winhello.c
- windows/build.ps1
We currently use LLVM's static analyser on our Linux and macOS builds. This PR adds equivalent functionality to our Windows build.
> windows: build with msvc's static analyser (/analyze)

- fuzz/wrap.c
- fuzz/wrapped.sym
- src/assert.c
- src/cred.c
SHA256_{Init,Update,Final} are marked as deprecated in OpenSSL 3.0. Given that alternatives exist in OpenSSL 1.1 and LibreSSL, switch to them as a first step towards OpenSSL 3.0 integration. Joint work with Dmitry Belyavskiy (@beldmit).
> Replace SHA256_* with EVP_* equivalents

- man/fido_cred_verify.3
- src/cred.c
Rework verify_sig (used by fido_cred_verify) to accept key types other than ES256, while making the code OpenSSL 3.0 compatible.
Diff from Dmitry Belyavskiy (@beldmit).
> cred: rework verify_sig

- src/ecdh.c
EVP_PKEY_CTX_add1_hkdf_info takes a const unsigned char * in OpenSSL 3, and a void * in OpenSSL 1.1. We pass a char *, so add an explicit cast to void * to satisfy both variations.
> ecdh: explicit cast to silence warning with OpenSSL 3.0

- src/es256.c
Use the EVP_PKEY_verify family of functions to make es256_verify_sig compatible with OpenSSL 3.0. Diff from Dmitry Belyavskiy (@beldmit).
> es256: make es256_verify_sig OpenSSL 3.0 compatible

- src/rs256.c
Use the EVP_PKEY_verify family of functions to make rs256_verify_sig compatible with OpenSSL 3.0. Diff from Dmitry Belyavskiy (@beldmit).
> rs256: make rs256_verify_sig OpenSSL 3.0 compatible

- fuzz/export.gnu
- fuzz/fuzz_assert.c
- man/CMakeLists.txt
- man/es256_pk_new.3
- regress/assert.c
- src/es256.c
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido/es256.h
The EC_KEY C type has been deprecated in OpenSSL 3.0, with EVP_PKEY as its successor. As such, define es256_pk_from_EVP_PKEY so that applications can migrate from es256_pk_from_EC_KEY.
Discussed with Dmitry Belyavskiy (@beldmit).
> es256: define es256_pk_from_EVP_PKEY

- src/assert.c
- src/cred.c
- src/eddsa.c
- src/es256.c
- src/extern.h
- src/rs256.c
Split *_verify_sig into *_pk_verify_sig (takes a *_pk_t) and *_verify_sig (takes a EVP_PKEY). This will allow *_verify_sig to be
used on attestation signatures as well (in an upcoming PR).
> Split *_verify_sig into EVP_PKEY components

- src/cbor.c
- src/cred.c
- src/eddsa.c
- src/es256.c
- src/fido/param.h
- src/fido/types.h
- src/rs1.c
- src/rs256.c
Verify a credential's attestation according to the 'alg' (algorithm) in the attestation statement. This is needed to support TPM attestation, which uses RSA instead of ECDSA (the only signature algorithm supported by libfido2 for Basic Attestation so far).
> Verify attestation according to attestation statement algorithm

- src/winhello.c
Parse the attestation object provided by Microsoft's webauthn.h instead of poking at various pointers in `WEBAUTHN_CREDENTIAL_ATTESTATION`, shrinking the number of lines of code while allowing the 'certInfo' and 'pubArea' parts of the attestation statement to be parsed.
> winhello: parse attestation object

- openbsd-compat/openbsd-compat.h
- src/CMakeLists.txt
- src/extern.h
- src/tpm.c
This PR adds basic TPM support, to be built upon as we encounter more real-world TPM use cases.
> winhello: add support for Windows Hello TPM 2.0 attestation

- src/netlink.c
Return an error if we fail to acquire a NFC target within 100ms.
> netlink: don't block indefinitely in fido_nl_get_nfc_target()

- src/dev.c
- src/extern.h
- src/nfc_linux.c
so that fido2-token -L now outputs:
```
ted:~/projects/libfido2$ build/tools/fido2-token -L                                                                      
nfc://sys/devices/pci0000:00/0000:00:14.0/usb3/3-3/3-3:1.0/nfc/nfc0: vendor=0x072f, product=0x2200 (ACS ACR122U PICC Interface)
/dev/hidraw4: vendor=0x1050, product=0x0406 (Yubico YubiKey FIDO+CCID)
ted:~/projects/libfido2$ build/tools/fido2-token -I nfc://sys/devices/pci0000:00/0000:00:14.0/usb3/3-3/3-3:1.0/nfc/nfc0 
proto: 0x00
major: 0x00
minor: 0x00
build: 0x00
caps: 0x04 (nowink, cbor, msg)
version strings: U2F_V2, FIDO_2_0, FIDO_2_1_PRE
extension strings: credProtect, hmac-secret
transport strings: nfc, usb
algorithms: es256 (public-key), eddsa (public-key)
aaguid: 149a20218ef6413396b881f8d5b7f1f5
options: rk, up, noplat, …
```
> nfc: work with nfc:// paths

- src/winhello.c
Microsoft's webauthn interface may be used to communicate with cross-platform authenticators even if WebAuthNIsUserVerifyingPlatformAuthenticatorAvailable() returns false. Fixes #382.
> winhello: fix detection

- src/dev.c
libfido2 may internally override the transport function (i.e. set
`io_own`) for some of its backends. As such, we must determine the
correct sigmask function by introspecting the transport and io
functions rather than erroring out if `io_own` is set.
> dev: allow use of fido_dev_set_sigmask() with nfc

- src/dev.c
- src/extern.h
- src/info.c
Take a copy of the device's timeout attribute and pass a reference to it instead of hard-coded `-1` ms.
This introduces a set of temporary stubs to pass a reference of the timeout to `fido_rx()` and `fido_rx_cbor_status()` until we are ready to change the signature of these functions.
> dev,info: pass timeout by reference

- .github/workflows/windows_builds.yml
- windows/build.ps1
- don't explicitly specify a cmake generator in windows/build.ps1; cmake has reasonable defaults;
- build on windows 2019, 2022.
> windows: build adjustments

- src/assert.c
- src/extern.h
While here, also prepare for `fido_do_ecdh()` accepting a timeout argument. `fido_do_ecdh()` calls into `fido_dev_authkey()`, which should ultimately also accept a timeout argument.
> assert: pass timeout by reference

- man/fido_dev_info_manifest.3
- src/hid_linux.c
- src/hid_osx.c
- src/hid_win.c
- src/nfc_linux.c
Some devices don't have associated vendor/product strings, e.g. Kensington's VeriMark Guard Fingerprint Key, as seen in #381. Instead of rejecting these devices, accept them with empty identifier strings, and do so consistently across Linux/macOS/Windows.
> Support devices without vendor/product strings

- man/CMakeLists.txt
- man/fido_dev_set_io_functions.3
- src/dev.c
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido.h
Sets an upper limit for how long libfido2 may block while communicating
with a device.
> dev: add fido_dev_set_timeout

- CMakeLists.txt
- examples/assert.c
- examples/cred.c
- examples/extern.h
- examples/reset.c
- examples/util.c
drop the existing signal-based timeout implementation in favour of the recently introduced fido_dev_set_timeout().
> examples: switch to fido_dev_set_timeout()

- src/iso7816.c
- src/iso7816.h
On CHERI, and thus Arm's experimental Morello prototype architecture,
pointers are represented as capabilities, which are unforgeable bounded
pointers, providing always-on fine-grained spatial memory safety. The
unforgeability is enforced through the use of tagged memory, with one
validity tag bit per capability-sized-and-aligned word in memory. This
means that storing a pointer to an unaligned location, which is not
guaranteed to work per the C standard, either traps or results in the
capability losing its tag (and thus never being dereferenceable again),
depending on how exactly the store is done (specifically, whether a
capability store or memcpy is used).
However, iso7816 itself does not need to be packed, and doing so likely
causes inefficiencies on existing architectures. The …
> iso7816: Avoid storing pointers in a packed structure

- src/tpm.c
add support for es256 credentials. the attestation algorithm is still limited to rs1. spec references are relative to https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part2_Structures_pub.pdf.
> tpm: add support for es256 credentials

- src/hid_osx.c
avoid IORegistryEntryGetPath() and io_string_t; the paths returned by the former can grow quite long, while the latter is defined as typedef char io_string_t[512]; fixes #462.
> hid_osx: handle devices with paths > 511 bytes

- CMakeLists.txt
- src/eddsa.c
- windows/build.ps1
- windows/const.ps1
- windows/release.ps1
https://marc.info/?l=openbsd-announce&m=163789626027148
Please note that:
- LibreSSL 3.4 defines `EVP_DigestVerify()`, so we need to adjust the compatibility shim in eddsa.c;
- The path to crypto-47.pdb has changed (due to changes in LibreSSL's CMakeLists.txt).
> windows: bump LibreSSL to 3.4.2

- src/winhello.c
Missing WINAPI leads to broken stacks after calling webauthn functions
on 32 bit Cygwin.  The reason is that GCC defaults to the cdecl
calling convention on 32 bit x86, while WINAPI is equivalent to the
stdcall calling convention.
> winhello: fix function typedefs for 32 bit x86

- man/fido_dev_info_manifest.3
- man/fido_dev_open.3
- man/fido_dev_set_io_functions.3
- src/dev.c
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido.h
- src/hid.c
fix https://github.com/Yubico/libfido2/issues/465
For the moment, I didn't provide any way to use _only_ custom transport functions -- it is still necessary to combine custom I/O functions (open and close, but not read or write) with custom transport functions (tx and rx).  This serves for my purposes, but it might be nice if the transport layer operated independently of the I/O layer.  Also, for the moment, the only way to set the device handle is via the I/O open function, which is only passed a path as an argument -- again, adequate for my purposes, but other applications might want simpler control from the caller over the device handle.  (Of course, you could snprintf("%p") and then sscanf it back!)
> Add missing support for custom transport functions

- src/bio.c
CTAP canonical CBOR encoding establishes that we must use the smallest representation possible for a given integer; as such, even though timo_ms is a uint32_t type, we must use cbor_build_uint() to encode it instead of cbor_build_uint32(), as the value may ultimately fit in a smaller integer type. Fixes #480.
> bio: fix CTAP canonical CBOR encoding

- .actions/build-bsd
Sets jq's exit status to 1 if the output is null.
> ci: handle jq query failing

- src/winhello.c
fallback to GetTopWindow() if GetForegroundWindow() fails, in case we are running as a service or background app on Windows.
> winhello: fallback to GetTopWindow()

- windows/release.ps1
This change adds following symbol files for static libraries in the output package folders:
`crypto-46.pdb, cbor.pdb, zlib.pdb, fido2.pdb`
> Adding static lib symbols to package folders

- .actions/build-linux-i686-w64-mingw32-gcc
- .actions/build-linux-openssl3-i686-w64-mingw32-gcc
- .actions/fuzz-linux
the unauthenticated git protocol on port 9418 (git://) is no longer supported by github.
> .actions: git -> https

- man/fido_assert_allow_cred.3
- man/fido_assert_new.3
- man/fido_assert_set_authdata.3
particularly in regard to core FIDO2 attributes vs. CTAP 2.0 extensions vs. CTAP 2.1 extensions.
> man/fido_assert*.3: adjust for concision, clarity

- CMakeLists.txt
- man/CMakeLists.txt
CMAKE_SOURCE_DIR might not equate PROJECT_SOURCE_DIR in scenarios where we are embedded in another cmake project; #512
> cmake: CMAKE_SOURCE_DIR -> PROJECT_SOURCE_DIR

- src/winhello.c
Per the CTAP protocol the "uv" capability indicates that the device is
capable of verifying the user within itself, while "clientPin" indicates
that the device is capable of accepting a PIN from the client.  WinHello
only supports "uv", but not "clientPin", but current libfido2 advertises
"clientPin", not "uv".  Change this in fido_winhello_get_cbor_info.
Signed-off-by: Corinna Vinschen <vinschen@redhat.com>
> Advertise "uv" capability, not "clientPin".

- src/fido.h
- src/fido/types.h
On UNIX-like systems, an application compiled using strict ISO C may
fail to build if it includes libfido2 headers due to `sigset_t` being
a POSIX extension. Determine whether `sigset_t` is defined by checking
for a known POSIX macro from the same header, hide the declaration of
`fido_dev_set_sigmask()` and `fido_sigset_t` otherwise.
> dev: restrict visibility of fido_dev_set_sigmask

- src/nfc_linux.c
Reset pointer after failed asprintf(), as its value is potentially undefined. Discussed with @LDVG.
> nfc_linux: reset pointer after failed asprintf()

- fuzz/wrap.c
- fuzz/wrapped.sym
when fuzzing, wrap asprintf (used in a couple of places) to ensure that failure is properly handled, and that the string pointer is
correctly reset by the caller.
> fuzz: wrap asprintf

- src/nfc_linux.c
we currently set it to 0x80, signalling support for NFCCTAP_GETRESPONSE (instruction 0x11), which we don't implement in libfido2; https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#nfc-ctap-msg
> nfc_linux: set p1 to 0 when sending a NFCCTAP_MSG apdu

- src/extern.h
- src/pcsc.c
use the reader name (potentially a long string) as the product string, and enumerate pcsc readers as 'pcsc0', 'pcsc1', ..., 'pcscN'.
> pcsc: use shorter paths

- src/CMakeLists.txt
- src/extern.h
- src/hid_osx.c
- src/nfc_linux.c
- src/pcsc.c
- src/util.c
while here, adapt callers of similar functions accordingly. shrinks the code a bit.
> rename hid_osx.c's to_uint64() to fido_to_uint64(), and move it to util.c

- src/pcsc.c
this allows fido_pcsc_manifest() to suppress the error and proceeed, which is the desired behaviour. prompted by macOS's SCardListReaders() returning a 1-byte buffer consisting of a zero byte when no reader is available.
> pcsc: return SCARD_E_NO_READERS_AVAILABLE if we fail to list_readers()

- src/pcsc.c
FIDO_MAXMSG (currently 2048 bytes) is overkill. 261 bytes are enough, but round the value to the nearest multiple of 8.
> pcsc: use a smaller buffer to store short APDUs

- src/extern.h
- src/pcsc.c
> pcsc: use 'pcsc://slotN' prefix for consistency with nfc, windows

- CMakeLists.txt
- openbsd-compat/bsd-asprintf.c
- openbsd-compat/openbsd-compat.h
Add a asprintf() compatibility shim so that we can use asprintf() on Windows. From OpenSSH via LibreSSL.
> openbsd-compat: add a asprintf() compatibility shim

- src/pcsc.c
shortens the code and allows us to drop two variables
> pcsc: use asprintf instead of snprintf + strdup

- .github/workflows/cifuzz_oss.yml
we already have separate asan and msan runners, but they use ubuntu's llvm-12, while oss-fuzz's cifuzz typically runs on newer llvm.
> actions/cifuzz: use asan, msan, and ubsan

- src/hid_freebsd.c
- src/hid_openbsd.c
- hid_openbsd: split copy_info from fido_hid_manifest for consistency with other manifest functions;
- hid_freebsd: zap early assignment of `olen` and log `close()` error.
> hid_{open,free}bsd: miscellaneous fixes

- src/eddsa.c
- eddsa_pk_from_ptr: check if resulting eddsa_pk_t is valid;
- eddsa_pk_from_EVP_PKEY: EVP_PKEY_base_id().
> eddsa: stricter checks when populating eddsa_pk_t types

- CMakeLists.txt
- windows/build.ps1
- windows/release.ps1
zlib on windows can exist as zlib, zlib1, zlibd, zlibd1, zlibstatic, or zlibstaticd. patch up the various names and work with zlib1 only.
> windows: patch up zlib's various names

- regress/assert.c
- regress/cred.c
- regress/dev.c
- regress/es256.c
- prefer openssl's BIO interface over fmemopen();
- undef NDEBUG;
- define _FIDO_INTERNAL;
- avoid casting integers to pointers.
> regress: portability fixes

- CMakeLists.txt
- src/rs1.c
- src/rs256.c
- windows/build.ps1
- windows/const.ps1
- windows/release.ps1
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.5.2-relnotes.txt
of particular relevance to us is that LibreSSL 3.5.2 defines EVP_MD_meth_dup() and treats EVP_MD as a opaque pointer.
> windows: bump LibreSSL to 3.5.2

- src/winhello.c
use the recently introduced WEBAUTHN_AUTHENTICATOR_HMAC_SECRET_VALUES_FLAG to support the hmac-secret extension in fido_dev_get_assert() via webauthn.dll (winhello). for some reason, only the 32-byte variation of hmac-secret appears to be supported.
> winhello: support hmac-secret in fido_dev_get_assert()

- regress/CMakeLists.txt
- regress/eddsa.c
- regress/es256.c
- regress/rs256.c
- src/rs256.c
- rs256_pk_to_EVP_PKEY: check RSA_bits();
- rs256_pk_from_ptr: check if resulting rs256_pk_t is valid;
- regress: add a couple of rs256 tests;
- regress: constify some pointers;
- rs256: fix rs256_pk_from_EVP_PKEY with OpenSSL 3.
> rs256: add tests, fix OpenSSL 3 compat

- fuzz/wrap.c
- fuzz/wrapped.sym
previous attempts were blocked by oss-fuzz running on xenial, which lacks getrandom(). hopefully that's no longer the case.
> fuzz: try to wrap getrandom() (again)

- fuzz/fuzz_pcsc.c
- src/extern.h
- src/nfc.c
- src/nfc_linux.c
- src/pcsc.c
select the fido applet on nfc/pcsc manifest. mainly to avoid the duplicate detection of CCID+HID yubikeys, but also to prevent non-fido smartcards or nfc tags from being listed. discussed with @LDVG.
> nfc/pcsc: select applet on manifest

- regress/CMakeLists.txt
- Compile `regress` against `${_FIDO2_LIBRARY}` so it links against the shared library when building with `BUILD_STATIC_LIBS=OFF`.
- Export the symbols required for `regress/compress`.
- Run the Linux CI tests for both static and dynamic libraries.
> regress: link/run against chosen library

- src/pin.c
see https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#authnrClientPin-pin-composition
> pin: max pin length is 63 bytes, as per spec

- tools/assert_get.c
- tools/cred_make.c
- tools/pin.c
there's no point in using 1024-byte buffers when the maximum allowed PIN length is 63; while here, make sure that fido2-{assert,cred,token} detect readpassphrase() truncation.
> tools: reduce stack usage; detect readpassphrase() truncation

- src/authkey.c
- src/bio.c
this PR is a continuation of #584:
> FIDO_MAXMSG (2048 bytes) is a bit too large to be allocated on the stack comfortably. while here, make sure to clear the buffer once we're done with it.
> authkey, bio: move reply buffer to the heap

- src/credman.c
- src/info.c
this PR is a continuation of #584:
> FIDO_MAXMSG (2048 bytes) is a bit too large to be allocated on the stack comfortably. while here, make sure to clear the buffer once we're done with it.
> credman, info: move reply buffer to the heap

- src/io.c
- src/largeblob.c
this PR is a continuation of #584:
> FIDO_MAXMSG (2048 bytes) is a bit too large to be allocated on the stack comfortably. while here, make sure to clear the buffer once we're done with it.
> io, largeblob: move reply buffer to the heap

- src/fallthrough.h
- src/u2f.c
`/* FALLTHROUGH */` might not be recognised by the compiler; pointed out by @jpalus in #591; discussed with @LDVG.
> use a portable way to annotate fallthroughs

- fuzz/README
- fuzz/wrap.c
add some words around fuzz/wrapped.sym, fuzz/wrap.c, and the probabilities chosen.
> fuzz: document the wrapping of symbols for fuzzing purposes

- src/hid_freebsd.c
Add support for the hidraw(4) driver introduced in FreeBSD 13.
As this driver is lacking support for USB_GET_DEVICEINFO at the
moment, fall back to an alternative to retrieve device information.
Once hidraw(4) gains support for USB_GET_DEVICEINFO, its results
will be used automatically.
> Support hidraw(4) on FreeBSD

- src/cbor.c
- src/extern.h
- src/info.c
in preparation for upcoming work in info.c (namely, supporting ctap 2.1's `forcePINChange`).
> move decoding of ctap cbor bools to cbor_decode_bool()

- fuzz/export.gnu
- fuzz/fuzz_mgmt.c
- man/CMakeLists.txt
- man/fido_cbor_info_new.3
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido.h
- src/fido/param.h
- src/fido/types.h
- src/info.c
- tools/token.c
parse field 0x12 (uvModality) of a ctap 2.1 authenticatorGetInfo response and make the result available through fido_cbor_info_uv_modality().
> add fido_cbor_info_uv_modality()

- src/es384.c
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido/es384.h
provide enough functionality for es384 keys to be allocated, deallocated, populated from memory, and converted to EVP_PKEY.
> es384: define a basic API, largely after es256

- src/cbor.c
- src/cred.c
while here, repair packed attestation with alg != COSE_ES256.
> support COSE_ES384 attestation

- src/config.c
If the command is not authenticated, attempting to toggleAlwaysUv on PIN
protected authenticators will always fail with FIDO_ERR_PIN_REQUIRED.
Regression introduced in 9024ff5c.
> config: authenticate subCommands without subCommandParams

- .github/workflows/bsd_builds.yml
OpenBSD 7.1 is now supported by builds.sr.ht (as per https://man.sr.ht/builds.sr.ht/compatibility.md#openbsd), so bump the version number in `.github/workflows/bsd_builds.yml` accordingly.
> actions: crank OpenBSD build to 7.1

- src/eddsa.c
- src/fido/eddsa.h
LibreSSL 3.7 will ship with Ed25519 support in EVP so the compatibility functions result in a symbol collision. Disable them.
> Disable EdDSA compat for LibreSSL 3.7

- tools/largeblob.c
Large blobs created with libfido2 >= 1.11.0 would otherwise when listed with `fido2-token -L -b` have an unknown RP ID and credential ID.
This mirrors the changes in 05cf927b11eeb5795f46219ff59219b3c9e5bc9b.
> tools: use raw inflate/rfc1951

- man/CMakeLists.txt
- man/fido_assert_allow_cred.3
- src/assert.c
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido.h
Useful for clients that may want to iterate over batches of credential ID:s after examining `maxCredentialCountInList`.
> assert: add fido_assert_empty_allow_list

- udev/70-u2f.rules
- udev/fidodevs
Running `lsusb` for both devices shows the following outputs which seem to be missing here:
ID 311f:4a2a eWBM eWBM G310H
ID 311f:4a2a TrustKey TrustKey G320H
---
P.S. My apologies for the [closed duplicate PR](https://github.com/Yubico/libfido2/pull/653). I renamed the branch after creating it.
> Add TrustKey `G310H`/`G320H` IDs

- fuzz/build-coverage
The build system no longer does this work for us. Accidentally left broken by #662.
> fuzz/coverage: explicitly pass libfuzzer options

- src/winhello.c
Wrap parameter in the LoadLibrary() call with the TEXT macro so that the code can be used in projects supporting wide strings
> Add support for unicode in winhello.c

- .github/workflows/bsd_builds.yml
I have no way to test this at the moment (can't push to Yubico/libfido2), but it should work.
> actions: bump OpenBSD build to 7.2

- fuzz/CMakeLists.txt
OSS-Fuzz require all projects to link with the fuzzing engine using CXX, even pure C projects [1]. Attempting to link with e.g. centipede will otherwise result in a set of undefined symbols.
[1] https://google.github.io/oss-fuzz/getting-started/new-project-guide/#Requirements
> fuzz/cmake: introduce FUZZ_LINKER_LANGUAGE

- src/winhello.c
According to https://learn.microsoft.com/en-us/cpp/c-runtime-library/data-type-constants?view=msvc-170, `SIZE_MAX` is either `2^32-1` or `2^64-1`, and according to https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/262627d8-3418-4627-9218-4ffe110850b2, `DWORD` is a 32-bit unsigned int. This implies a `DWORD > SIZE_MAX` comparison would always be false.
I make this finding in a Cygwin environment.
> Removes always false integer comparison

- src/winhello.c
Additional error mapping ...
Map Windows error codes ERROR_CANCELLED, NTE_USER_CANCELLED to FIDO_ERR_OPERATION_DENIED
> Expose user cancelation of the Windows Hello dialog

- man/CMakeLists.txt
- man/fido_assert_set_authdata.3
- src/assert.c
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido.h
- src/fido/types.h
- src/winhello.c
define fido_assert_set_winhello_appid(), a special-purpose function to pass a u2f appid to windows hello. this function is necessary because webauthn.dll does not allow authenticators to be probed silently, which is how u2f appids are handled in ctap.
without fido_assert_set_winhello_appid(), the only way to support u2f appid on windows is to expose users to webauthn.dll's ux twice; once for each call to fido_dev_get_assert(3).
tested on windows 11 pro insider preview build 25324.rs_prerelease.230317-1418 with webauthn.dll version 5.
> winhello: support u2f appid

- .actions/build-osx-clang
- .actions/fuzz-linux
- .github/workflows/macos_builds.yml
With OpenSSL 1.1.1's EOL around the corner (2023-09-11, according to https://www.openssl.org/policies/releasestrat.html), this PR switches libfido2's fuzz and macOS builds to use OpenSSL 3.0.
N.B. we still need to update https://github.com/google/oss-fuzz.
> actions: switch fuzz, macos builds to OpenSSL 3.0

- .github/workflows/alpine_builds.yml
- .github/workflows/bsd_builds.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/cygwin_builds.yml
- .github/workflows/linux_builds.yml
- .github/workflows/linux_fuzz.yml
- .github/workflows/macos_builds.yml
- .github/workflows/openssl3.yml
- .github/workflows/windows_builds.yml
Silences warnings on Node.js 12 actions being deprecated.
> ci: bump actions/checkout

- CMakeLists.txt
We are using `VERSION_GREATER_EQUAL` [1] which was added in CMake 3.7
(released in November 2016). The distributions that we perform releases
for are all running at least this version, further substantiated by the fact
that we've used this feature since libfido2 1.9.0 (released in October
2021).
Moreover, this change silences a warning on modern CMake versions that
compatilibity with versions less than CMake 3.5 is going to be removed
in a future CMake release [2].
While here, fix another warning that `cmake_minumum_required()` has to
be called before invoking any other command, see note in [1].
[1] https://cmake.org/cmake/help/latest/command/if.html#version-greater-equal
[2] https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#policy-settings
> cmake: bump cmake_minimum_required()

- man/fido2-assert.1
- man/fido2-cred.1
- tools/assert_get.c
- tools/cred_make.c
- tools/extern.h
- tools/fido2-assert.c
- tools/fido2-cred.c
A flag used to interpret the first line of input as raw client data rather than a hash of the client data. This is useful for `fido2-cred -M` and `fido2-assert -G` under the Windows Hello backend.
> tools: add FLAG_CD

- .github/workflows/macos_builds.yml
Brew no longer officially supports macOS Big Sur, resulting in [CI pipelines taking almost 5 hours to complete](https://github.com/Yubico/libfido2/actions/runs/6767944187/job/18391442595).
> actions: drop the macos-11 runner

- .github/workflows/macos_builds.yml
set HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK, so that 'brew install' does not imply the upgrade or reinstallation of dependent packages. this is needed as github actions' image comes with a significant amount of pre-installed packages, and given we install llvm and zlib, a bunch of unrelated packages were being reinstalled. the corollary is that it is now our responsibility to manually upgrade/reinstall any dependents we are interested in. at the moment that's an empty set, and while it is likely to remain that way, here's a note of caution to future readers.
> actions/build-osx-clang: tweak brew

- src/hid_osx.c
One invocation of `CFRunLoopRunInMode()` may fire `report_callback()`
multiple times. In such a case, the next call to `fido_hid_read()` may
block for the full duration of the timeout. We can handle this by
querying the (non-blocking) pipe for any readily available data on
entering `fido_hid_read()` and fall back to executing the run loop if it
was empty.
Debugged with @elibon99 and @martelletto.
Resolves #763
> osx: handle report_callback() firing multiple times

- windows/const.ps1
Seems like the powershell `Invoke-WebRequest` command to download LibreSSL is failing - I suspect the URL being used is being blocked, as the URL works fine when opened from a browser, but does not when using Invoke-WebRequest.
I was able to workaround this by changing the URL in windows\const.ps1 from `https://cloudflare.cdn.openbsd.org/pub/OpenBSD/LibreSSL` to `https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/`, which works with `Invoke-WebRequest`
> Change URL for LibreSSL dependency to avoid issues with the windows build

- windows/release.ps1
> windows: do not rename static PDB

- src/hid_netbsd.c
> hid_netbsd: move null pointer check before dereference

- src/cbor.c
- src/cred.c
- src/export.gnu
- src/export.llvm
- src/export.msvc
- src/fido.h
- src/fido/types.h
According to webauthn spec the x5c object under attStmt is of array type. But current code stores only the leaf certificate and discards the other certificates - reported as #749. This patch attempts to fix that. 
Summary of changes,
- `x5c` object under `fido_attstmt` is `fido_blob_array_t` type.
- `decode_x5c` and `fido_cred_set_x509` is updated to store as array.
- `fido_cred_x5c_ptr` and `fido_cred_x5c_len` are updated to retain backward compatibility; they now work with first certificate in the list.
- New API `fido_cred_x5c_list_count` added to return number of certificates in the x5c.
- New API `fido_cred_x5c_list_ptr` added to return requested certificate data in the x5c.
- New API `fido_cred_x5c_list_len` added to return byte length of requested certificate in the x5c.
> Change attstmt to handle x5c array/list

- .actions/build-linux-i686-w64-mingw32-gcc
- .actions/build-linux-openssl3-i686-w64-mingw32-gcc
- .actions/fuzz-linux
- fuzz/Dockerfile
- windows/const.ps1
libcbor 0.11.0 was released on 2024-02-04: https://github.com/PJK/libcbor/releases/tag/v0.11.0.
> actions: bump libcbor to v0.11.0

- windows/build.ps1
- windows/cygwin.ps1
If the default home directory ~/.gnupg does not exist, GnuPG creates this directory and a common.conf file with "use-keyboxd". If the option use-keyboxd is enabled in common.conf, no keyrings are used at all and keys are all maintained by the keyboxd process in its own database. This seemingly includes any keyring specified via the --keyring option and this breaks our signature verification of dependencies that we download in our Windows pipelines (see e.g. https://github.com/Yubico/libfido2/actions/runs/8082292785/job/22083086167#step:3:23).
> actions: disable use-keyboxd

- src/rs1.c
- src/rs256.c
In all versions of OpenSSL, EVP_sha{1,256}() return a pointer to static read-only data. There is no need to copy that data into a buffer that is immediately freed after use.
In LibreSSL and OpenSSL 1.x, EVP_PKEY_CTX_set_signature_md() is a wrapper around EVP_PKEY_ctrl() whose void * argument isn't const (contrary to the documented signature), so we need to cast const away in some way. This preserves rs*_get_EVP_MD() to contain the pragma pollution necessary due to -Werror -Wcast-qual.
The negative performance impact of calling EVP_sha*() multiple times called out in the OpenSSL 3.x documentation should not apply in this code.
Closes: #794
> Simplify getting an EVP_MD for all OpenSSL forks

- tools/credman.c
If first allocation succeeds and the 2nd fails, the `id` variable may be allocated and not freed. It's probably near to impossible case but it's worth fixing it for automation scan's sake
> Fix potential memory leak

- .github/workflows/linux_fuzz.yml
This reverts commit f80654cfc523ef3f8ca24c9bac5aa5811189f999 since actions/runner-images#9491 was closed.
> Revert temporary ASLR workaround

- .github/workflows/macos_builds.yml
https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/
> ci: add macos-14 runner

- .actions/build-bsd
- .github/workflows/bsd_builds.yml
While here we had to also disambiguate which LLVM and scan-build version to use.
> actions: bump FreeBSD, OpenBSD versions

- fuzz/fuzz_attobj.c
- fuzz/mutator_aux.c
Re: https://github.com/google/oss-fuzz/pull/11918
> fuzz: pacify MSAN

- .actions/build-bsd
- .actions/build-osx-clang
- .actions/run-shellcheck
- .github/workflows/shellcheck.yml
- man/check.sh
- tools/fido2-unprot.sh
- tools/include_check.sh
- tools/test.sh
add a shellcheck workflow and implement required fixes. while here, add a couple more tests to `tools/test.sh`.
> shellcheck workflow + fixes

- src/nfc.c
> nfc: specify cla on get response

- src/fido/param.h
- src/u2f.c
According to u2f spec: https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-raw-message-formats-v1.2-ps-20170411.html#status-codes, U2F security keys can return `0x6700` in addition to `0x6A80` when given invalid key handles.
This occurs to our internally developed security keys when the key handle is too long.
> U2F key_lookup: do not fail upon SW_WRONG_LENGTH (0x6700)

- src/nfc.c
Some cards erroneously interpret Le=0 as requesting no response data. When this happens, they send a 61nn response instead. We can workaround this by asking for the remaining data.
Resolves #818.
> nfc: chain rapdus in rx_init

- man/fido2-assert.1
- man/fido2-cred.1
> man: specify es384 as a valid type for fido2-{cred,assert}

- examples/cred.c
Some attestation format, e.g. `packed`, allows self attestation [1]. And when that happens, `fido_cred_x5c_ptr` would be `NULL`, making `fido_cred_verify` fail.
[1] https://w3c.github.io/webauthn/#sctn-packed-attestation
> [examples/cred] Support self attestation

- src/aes256.c
Only decryption should check `len < 16`.
> Allow len < 16 for aes256-gcm encryption

- windows/build.ps1
See for example https://github.com/actions/runner-images/issues/10981
Failing pipeline: https://github.com/Yubico/libfido2/actions/runs/12120784303/job/33790258713#step:3:159
While here, use the -A Arch,version= syntax since CMake may ignore
CMAKE_SYSTEM_VERSION.
> ci: pin Windows SDK for ARM builds

- .github/workflows/codeql-analysis.yml
CodeQL action v2 will be deprecated on 2024-12-05.
> ci: update CodeQL

- fuzz/CMakeLists.txt
Triviality, but it avoids triggering more "obscure" errors.
> cmake, add check on FUZZ_LDFLAGS

- .github/workflows/macos_builds.yml
Note that the macos-15 runner is in public preview.
> ci: bring in macos-15 runner

- .github/workflows/cifuzz_oss.yml
v3 is [closing down by EOM](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/); none of the [breaking changes](https://github.com/actions/upload-artifact/tree/65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08?tab=readme-ov-file#breaking-changes) appear relevant to us.
> ci: bump upload-artifact to v4

- src/nfc.c
Fixes some scenarios for PCSC FIDO2 tokens in integrated smartcard readers.
This fix was proposed by @LDVG in https://github.com/Yubico/libfido2/discussions/855.
> nfc: only append Le field in final APDU segment

- CMakeLists.txt
- NEWS
- windows/build.ps1
While here, tweak some of the release options.
> NEWS: add 1.16.0 blurb

- man/fido2-token.1
When you request the largeBlob based on the blob's base64-encoded 32 byte GCM key, the ctap standard does not require to get any pinUvAuthToken, as the largeBlob command can be sent directly. `fido2-token` does not require a PIN or equivalent user-verification gesture in this case. This commit just updates the documentation, to match the actual behavior.
The alternative command `fido2-token -G -b -n` does indeed first call credentialManagement to look up the key and therefore needs a token with the appropriate permission, so for the alternative command, this sentence is correct.
> manpage fido2-token.1: `fido2-token -G -b -k` does not require UV

- windows/const.ps1
[LibreSSL 4.1.0](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-4.1.0-relnotes.txt) was released Apr 30th, 2025
> windows: bump libressl to 4.1.0

- windows/build.ps1
- windows/cygwin.ps1
In CI, we're using gpg bundled with git which suddenly started refusing the GNUPGHOME directory we've had to create. It does works with relative paths using forward slash path separators.
Additionally tested using a Windows VM with gpg4win.
> windows: use forward slash path separators with gpg

- .github/workflows/macos_builds.yml
See https://github.com/actions/runner-images?tab=readme-ov-file#available-images
> ci: macos-13 runner is deprecated
