Yubico/libfido2

udev/70-u2f.rules
=> udev: add eWBM - Goldengate 450 and 500

tools/sk-libfido2.c
I've just added the matching code to openssh-current
=> sk-libfido v2 (ed25519 support)

udev/70-u2f.rules
Add support for the Nitrokey FIDO2 and Safetech SafeKey
Fixes https://github.com/Nitrokey/nitrokey-fido2-firmware/issues/23
=> Support Nitrokey FIDO2

src/io.c
This is not a requirement for libfido2 since standard fido2/u2f commands never have a non-empty payloads. Yet I think it is good to add the proper handling to prevent future suprise.
=> let fido_tx handle properly for empty payloads as well

src/assert.c, src/cbor.c, src/cred.c, src/extern.h
=> Fix self attestation with EdDSA

.github/workflows/cifuzz_oss.yml
Read more here: https://google.github.io/oss-fuzz/getting-started/continuous-integration/
=> Try out CIFuzz from oss-fuzz

examples/info.c, fuzz/export.gnu, fuzz/fuzz_mgmt.c, man/CMakeLists.txt, man/fido_cbor_info_new.3, src/export.gnu, src/export.llvm, src/export.msvc, src/fido.h, src/fido/types.h, src/info.c, tools/token.c
Parse firmware version advertised in getInfo (optional)
=> CTAP firmware version support in getInfo

src/es256.c
I believe these surrounding calls should be made per [OpenSSL's manpages](https://www.openssl.org/docs/manmaster/man3/BN_CTX_get.html).
=> add surrouding BN_CTX_start|end calls for BN_CTX_get

src/pin.c
Fixes #154. Exploratory for now; do not merge.
=> use COSE_ECDH_ES256 with CTAP_CBOR_CLIENT_PIN; gh#154

.github/workflows/linux_builds.yml, .github/workflows/linux_fuzz.yml, .github/workflows/macos_builds.yml, .github/workflows/scan.yml, .travis/build-linux-clang, README.adoc
Reusing existing travis scripts.
=> CI: convert linux builds, fuzzing and mac build to Github Actions

udev/70-u2f.rules, udev/fidodevs
Added support for the MIRKey.
Thanks
=> udev/fidodevs: Added PID to fidodevs for the MIRKey

openbsd-compat/time.h, src/hid_openbsd.c, tools/util.c
No idea if this is the right thing to do but now it builds and the other builds seem happy too :)
=> make master build on OpenBSD current

README.adoc
* remove link to fido2-native project until it gets further
=> doc: sync bindings

udev/70-u2f.rules, udev/fidodevs
Matches https://github.com/Yubico/libu2f-host/commit/443d2cea29fd4d9a9fa39b12d6556c85440cd8b
=> udev: add ledger pids

udev/70-u2f.rules, udev/fidodevs
K33 and K44, from: https://github.com/Yubico/libu2f-host/commit/f9b2e731ae9f41f8cd1f98587dc4de620b7a9471
=> udev: additional feitian keys

CMakeLists.txt
See https://cmake.org/cmake/help/latest/policy/CMP0083.html
=> cmake: help cmake add PIE flags required for linking

CMakeLists.txt, man/CMakeLists.txt, man/fido_dev_set_io_functions.3, openbsd-compat/time.h, src/dev.c, src/export.gnu, src/export.llvm, src/export.msvc, src/extern.h, src/fido.h, src/fido/types.h, src/hid_freebsd.c, src/hid_hidapi.c, src/hid_linux.c, src/hid_netbsd.c, src/hid_openbsd.c, src/hid_osx.c, src/hid_unix.c, src/hid_win.c, src/netlink.c, src/nfc_linux.c
https://github.com/Yubico/libfido2/issues/251
=> New function fido_dev_set_sigmask.

.actions/build-linux-clang, .actions/build-linux-gcc, .github/workflows/alpine_builds.yml
This should allow us to test if libfido2 builds with musl.
=> workflows: add workflow for alpine

fuzz/fuzz_assert.c, fuzz/fuzz_cred.c, fuzz/fuzz_mgmt.c
Note, base branch is `credblobs` until #285 is merged. Marking this as draft until then.
=> fuzz: add fuzzing of credBlobs and largeBlobKeys

src/cred.c
=> cred: use fido_blob_reset() in a few more places

src/bio.c, src/credman.c
=> bio, credman: use fido_blob_reset() in more places

src/pin.c, src/u2f.c
=> pin, u2f: use fido_blob_reset() in more places

src/winhello.c
=> winhello: use fido_cbor_info_reset()

examples/README.adoc, man/fido2-assert.1, man/fido2-cred.1, man/fido2-token.1, man/fido_bio_dev_get_info.3, man/fido_bio_template.3, man/fido_credman_metadata_new.3, man/fido_dev_enable_entattest.3
=> ctap 2.1: miscellaneous documentation tweaks

src/assert.c, src/cred.c
=> use fido_blob_set in more places

src/CMakeLists.txt, src/extern.h, src/info.c, src/types.c, src/winhello.c
Move code dealing with internal types from info.c and winhello.c to types.c. No functional change (intended).
=> Move code dealing with internal types to types.c

man/CMakeLists.txt, man/fido_cred_new.3, man/fido_cred_set_authdata.3, man/fido_cred_verify.3, man/fido_dev_enable_entattest.3
The documentation side of #359.
=> man: document FIDO_EXT_MINPINLEN ("minPinLen") functions

CMakeLists.txt, fuzz/export.gnu, man/fido2-token.1, openbsd-compat/openbsd-compat.h, openbsd-compat/strsep.c, tools/CMakeLists.txt, tools/config.c, tools/extern.h, tools/fido2-token.c, tools/token.c
Code mostly from @kongeo with bugs by me.
=> tools: expose FIDO 2.1 "minPinLen" in fido2-token

fuzz/export.gnu, fuzz/fuzz_mgmt.c
Code from @kongeo with bugs by me.
=> fuzz fido_dev_set_pin_minlen_rpid()

src/cred.c
Support es256, rs256, and eddsa attestation signatures in fido_cred_verify().
=> Support es256, rs256, and eddsa attestation signatures

regress/dev.c
test that fido_dev_close() returns FIDO_ERR_INVALID_ARGUMENT on a freshly allocated device as well as on an already closed device.
=> regress: test fido_dev_close()

src/hid_openbsd.c
Uses the fido_hid_unix_wait() implementation.
Tested on openbsd 6.7+6.9.
=> hid_openbsd: support fido_dev_set_sigmask()

.actions/build-bsd
=> actions: build with llvm's scan-build on openbsd

fuzz/fuzz_assert.c, fuzz/fuzz_bio.c, fuzz/fuzz_cred.c, fuzz/fuzz_credman.c, fuzz/fuzz_hid.c, fuzz/fuzz_largeblob.c, fuzz/fuzz_mgmt.c, fuzz/fuzz_netlink.c, fuzz/libfuzzer.c, fuzz/mutator_aux.c, fuzz/mutator_aux.h
tested using our fuzzing infrastructure; confirmed by cifuzz/oss-fuzz.
=> fuzz: drop no longer needed msan instrumentation

src/cbor.c
when building the hmac-secret map of an assertion, only include the pinUvAuthProtocol (0x04) key if the pin protocol used is not 1. doing so is spec compliant and allows us to better handle authenticators that aren't, as discussed in #395.
=> cbor: optionally include pinUvAuthProtocol (0x04)

.actions/build-bsd
while here, adopt terser language
=> actions: build with llvm's scan-build on freebsd

fuzz/Dockerfile, fuzz/Makefile
=> fuzz: update Dockerfile to LLVM 12

regress/dev.c
=> regress: test fido_dev_set_timeout()

.github/workflows/windows_builds.yml, windows/build.ps1, windows/const.ps1, windows/release.ps1
rework build.ps1 into smaller, composable parts, and leverage that to run the various windows builds in parallel.
=> windows: rework build script

src/winhello.c
move the api version check inside webauthn_load() to ensure it
always happens when the windows://hello pseudo-device is opened,
which allows winhello_manifest() to be replaced with a call to
webauthn_load(). improves debug output; no functional change.
=> winhello: always perform api version check

src/webauthn.h
opening a PR for visibility + CI
=> webauthn.h: sync with microsoft/webauthn d6650d5f1

src/winhello.c
=> winhello: check winhello_get_assert() against FIDO_OK

man/eddsa_pk_new.3, man/es256_pk_new.3, man/rs256_pk_new.3
- eddsa_pk_new: fix reference to eddsa_pk_from_EVP_PKEY();
- es256_pk_new: fix reference to es256_pk_from_EVP_PKEY();
- rs256_pk_new: sort .Nm section.
=> man: miscellaneous fixes

man/CMakeLists.txt, man/check.sh, man/fido_assert_set_authdata.3, man/fido_assert_verify.3, man/fido_cbor_info_new.3, man/fido_dev_get_assert.3, man/fido_dev_make_cred.3, man/fido_dev_set_io_functions.3
add a script to spot inconsistencies in the documentation, and fix some of the findings
=> man: add auxiliary script + fixes

src/dev.c, src/extern.h, src/nfc.c
while here, move the code from dev.c to nfc.c
=> dev: abstract check for nfc paths

udev/70-u2f.rules, udev/fidodevs
See: https://github.com/solokeys/solo2
See: https://github.com/solokeys/solo2/blob/main/70-solo-bee.rules
Cc @conorpp
=> udev: add SoloKey v2 ID

.actions/build-bsd, .github/workflows/alpine_builds.yml, .github/workflows/codeql-analysis.yml, .github/workflows/linux_builds.yml, .github/workflows/openssl3.yml, CMakeLists.txt
temporarily enable USE_PCSC in GitHub Action builds. to be revisited before release.
=> enable USE_PCSC everywhere modulo fuzz builds

regress/es256.c, src/es256.c
=> es256: stricter checks when populating es256_pk_t types

README.adoc
- mention NFC in intro;
- unfold Releases from Installation;
- highlight Dependencies;
- mention Windows;
- add pointers to Issues and Discussions;
- list build-time options.
=> README: shuffle, tweak for clarity

.github/workflows/bsd_builds.yml, .github/workflows/codeql-analysis.yml, .github/workflows/linux_builds.yml, .github/workflows/linux_fuzz.yml, .github/workflows/openssl3.yml, src/hid_win.c
use ubuntu-22.04 where possible (everywhere modulo containers)
=> actions: use ubuntu-22.04 where possible

CMakeLists.txt, src/CMakeLists.txt, tools/CMakeLists.txt
be cognizant of the fact that stack space might be a scarce resource by ensuring we don't cross over half a page in any particular frame.
=> build with -Wframe-larger-than=2047

src/hid_linux.c
failure to do so will cause a process to observe hid frames exchanged by a previous holder of the lock. while there's code in rx_preamble() to skip frames addressed to a different cid (allowing for a degree of synchronisation), it is unclear what should happen to ctap broadcast frames not addressed to the current process. debugged and discussed with @LDVG.
=> hid_linux: reopen hidraw(4) after flock(2)

examples/README.adoc, examples/cred.c, src/CMakeLists.txt, src/cbor.c, src/cred.c, src/es384.c, src/extern.h, src/fido/param.h, src/fido/types.h, src/winhello.c
first step towards COSE_ES384 support
=> allow creation of COSE_ES384 credentials

src/es384.c, src/export.gnu, src/export.llvm, src/export.msvc, src/extern.h, src/fido/es384.h
based on existing es256 counterparts
=> es384: introduce es384_{pk_from_EC_KEY,verify_sig}

src/assert.c
split fido_get_signed_hash() into smaller subroutines and rework the code to make it clearer which COSE_* algorithms are supported.
=> assert: prepare the ground for es384 support

tools/assert_verify.c, tools/extern.h, tools/test.sh, tools/token.c, tools/util.c
add es384 support to fido2-{assert,cred,token}; adapt test script accordingly.
=> tools: add es384 support

man/CMakeLists.txt, man/fido_cred_exclude.3, src/cred.c, src/export.gnu, src/export.llvm, src/export.msvc, src/fido.h
=> cred: add fido_cred_empty_exclude_list

.github/workflows/linux_builds.yml, .github/workflows/openssl3.yml
- build with clang-15 on linux;
- build openssl3 with clang-15.
=> actions: add clang-15 builds

.actions/fuzz-linux, .github/workflows/cifuzz_oss.yml, .github/workflows/linux_fuzz.yml, fuzz/README, fuzz/fuzz_assert.c, fuzz/fuzz_bio.c, fuzz/fuzz_cred.c, fuzz/fuzz_credman.c, fuzz/fuzz_hid.c, fuzz/fuzz_largeblob.c, fuzz/fuzz_mgmt.c, fuzz/fuzz_netlink.c, fuzz/fuzz_pcsc.c
- update clang to clang-15;
- bump libcbor to 0.10.1.
=> fuzz: update clang to clang-15, bump libcbor to 0.10.1

.actions/build-linux-i686-w64-mingw32-gcc, .actions/build-linux-openssl3-i686-w64-mingw32-gcc, .github/workflows/alpine_builds.yml, LICENSE, fuzz/Dockerfile, fuzz/Makefile, windows/build.ps1, windows/const.ps1
Follow up of  #659.
While here, bump the license copyright.
=> misc: bump more occurrences of libcbor

.github/workflows/linux_builds.yml, .github/workflows/linux_fuzz.yml, .github/workflows/openssl3.yml
LLVM 16.0.0 was released last week: https://discourse.llvm.org/t/llvm-16-0-0-release/69326
=> actions: update to clang-16

fuzz/export.gnu, fuzz/fuzz_assert.c, man/CMakeLists.txt, man/fido_assert_new.3, regress/assert.c, src/assert.c, src/export.gnu, src/export.llvm, src/export.msvc, src/fido.h, src/fido/types.h
=> assert: introduce `fido_assert_authdata_raw_{ptr,len}()`

CMakeLists.txt, NEWS
While here, disable USE_PCSC in preparation for release.
=> NEWS: add 1.14.0 blurb

fuzz/libfuzzer.c
IWYW principle: include what you wants.
=> Include limits.h for PATH_MAX

.github/workflows/bsd_builds.yml
=> actions: bump OpenBSD build to 7.3

tools/token.c
Not sure if this information is useful, just added it for completeness.
=> Adds max cred blob length to -I

.actions/fuzz-linux
Brings fuzzing job build times down a bit.
=> actions: more parallel builds

CMakeLists.txt, man/CMakeLists.txt
=> man: do not build manual pages under MSVC

.github/workflows/macos_builds.yml
See https://github.com/Yubico/libfido2/actions/runs/11139583817/job/30956566565?pr=822#step:3:21
=> ci: drop macos-12 runner

man/fido2-assert.1, man/fido2-cred.1
=> man: clarify CBOR encoded authenticator data

.actions/build-linux-i686-w64-mingw32-gcc, .actions/build-linux-openssl3-i686-w64-mingw32-gcc, .actions/fuzz-linux, fuzz/Dockerfile, windows/const.ps1
=> ci: bump libcbor to v0.12.0

.github/workflows/cygwin_builds.yml, .github/workflows/windows_builds.yml, windows/build.ps1, windows/release.ps1
- actions: move cygwin to windows-2025;
- actions: build libfido2 on windows-2025 as well.
=> windows tweaks

fuzz/fuzz_assert.c, fuzz/fuzz_attobj.c, fuzz/fuzz_bio.c, fuzz/fuzz_cred.c, fuzz/fuzz_credman.c, fuzz/fuzz_hid.c, fuzz/fuzz_largeblob.c, fuzz/fuzz_mgmt.c, fuzz/fuzz_netlink.c, fuzz/fuzz_pcsc.c, fuzz/mutator_aux.c, fuzz/pcsc.c, fuzz/udev.c
like regress/, fuzz/ needs working assertions
=> fuzz: undef NDEBUG
